services:
  express-app:
    build: .
    container_name: express-mongodb-redis-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/redis-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - JWT_SECRET=jwt-secret
      - CACHE_EXPIRY=3600
    networks:
      - redis-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - redis-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
